package org.example.part2.tracing;

public enum RBTreeTracePoint {
    // INSERT
    INSERT_EMPTY_TREE,
    INSERT_GO_LEFT,
    INSERT_GO_RIGHT,
    INSERT_PLACED,

    // FIX AFTER INSERT
    FIX_UNCLE_RED,
    FIX_ROTATE_LEFT_CASE,
    FIX_ROTATE_RIGHT,
    FIX_ROTATE_LEFT,
    FIX_ROTATE_RIGHT_CASE,

    // FIND
    FIND_MATCH,
    FIND_GO_LEFT,
    FIND_GO_RIGHT,
    FIND_NOT_FOUND,

    // DELETE
    DELETE_NOT_FOUND,
    DELETE_FOUND,
    DELETE_TWO_CHILDREN,
    DELETE_FIX_NEEDED,

    // FIX AFTER DELETE
    DELETE_FIX_SIBLING_RED,
    DELETE_FIX_SIBLING_BLACK_KIDS,
    DELETE_FIX_SIBLING_RIGHT_RED,
    DELETE_FIX_DONE
}
